name: Run Databricks Notebook1

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI


jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Trigger Databricks Job
      run: |
        curl -X POST https://dbc-9f11103b-bf2c.cloud.databricks.com/api/2.1/jobs/run-now \
        -H "Authorization: Bearer dapi852b1f295a0dc2e389f8377448a829e7" \
        -H "Content-Type: application/json" \
        -d '{
              "job_id": 255293602963038
            }'
